// AUTO-GENERATED by tools/extract-comfy-locale.mjs — do not edit by hand.
// Extracted from the live ComfyUI frontend (locale: zh-CN) so node titles,
// widget labels and port labels match what ComfyUI itself renders.
// ComfyUI localises these at render time; they are NOT in the workflow JSON.
export const TITLES = {
  "SaveVideo": "保存视频",
  "ResolutionSelector": "分辨率选择器",
  "LoadImage": "加载图像",
  "ImageScaleToTotalPixels": "缩放图像（像素）",
  "GetImageSize": "获取图像尺寸",
  "VAELoader": "加载VAE",
  "VAEDecodeAudio": "VAE解码（音频）",
  "VAEDecode": "VAE解码",
  "KSamplerSelect": "K采样器选择",
  "BasicScheduler": "基本调度器",
  "SamplerCustomAdvanced": "自定义采样器（高级）",
  "BasicGuider": "基本引导器",
  "UNETLoader": "UNet加载器",
  "CLIPLoader": "加载CLIP",
  "RandomNoise": "随机噪波",
  "CreateVideo": "创建视频",
  "ComfyMathExpression": "数学表达式",
  "MiniMaxH3ReferenceToVideo": "MiniMax H3 参考转视频",
  "LoraLoaderModelOnly": "LoRA加载器（仅模型）",
  "MinimaxHailuo03FirstLastFrameNode": "MiniMax H3 首帧-末帧生成视频"
};

export const WIDGET_LABELS = {
  "SaveVideo": {
    "filename_prefix": "文件名前缀",
    "format": "格式",
    "format.codec": "编解码器",
    "codec": "编码器"
  },
  "ResolutionSelector": {
    "aspect_ratio": "宽高比",
    "megapixels": "百万像素",
    "multiple": "倍数",
    "preview": "preview"
  },
  "MarkdownNote": {
    "text": "text"
  },
  "LoadImage": {
    "image": "图像",
    "upload": "选择文件上传"
  },
  "ImageScaleToTotalPixels": {
    "upscale_method": "缩放算法",
    "megapixels": "像素数量",
    "resolution_steps": "分辨率步数"
  },
  "GetImageSize": {},
  "VAELoader": {
    "vae_name": "vae名称"
  },
  "VAEDecodeAudio": {},
  "VAEDecode": {},
  "KSamplerSelect": {
    "sampler_name": "采样器名称"
  },
  "BasicScheduler": {
    "scheduler": "调度器",
    "steps": "步数",
    "denoise": "降噪"
  },
  "SamplerCustomAdvanced": {},
  "BasicGuider": {},
  "UNETLoader": {
    "unet_name": "UNet名称",
    "weight_dtype": "数据类型"
  },
  "CLIPLoader": {
    "clip_name": "CLIP名称",
    "type": "类型",
    "device": "设备"
  },
  "RandomNoise": {
    "noise_seed": "噪波随机种",
    "control_after_generate": "生成后控制"
  },
  "CreateVideo": {
    "fps": "帧率",
    "bit_depth": "bit_depth",
    "color_space": "color_space",
    "codec": "codec"
  },
  "ComfyMathExpression": {
    "expression": "表达式"
  },
  "PrimitiveFloat": {
    "value": "值"
  },
  "MiniMaxH3ReferenceToVideo": {
    "prompt": "提示词",
    "width": "宽度",
    "height": "高度",
    "length": "长度",
    "ref_image_size": "参考图像尺寸"
  },
  "PrimitiveStringMultiline": {
    "value": "值"
  },
  "ComfySwitchNode": {
    "switch": "切换"
  },
  "PrimitiveInt": {
    "value": "数值",
    "fixed": "生成后控制"
  },
  "LoraLoaderModelOnly": {
    "lora_name": "LoRA名称",
    "strength_model": "模型强度"
  },
  "PrimitiveBoolean": {
    "value": "值"
  },
  "MinimaxHailuo03FirstLastFrameNode": {
    "model": "model",
    "model.prompt": "prompt",
    "model.resolution": "resolution",
    "model.duration": "duration",
    "seed": "seed",
    "control_after_generate": "生成后控制",
    "watermark": "watermark"
  }
};

export const INPUT_LABELS = {
  "SaveVideo": {
    "video": "视频",
    "filename_prefix": "文件名前缀",
    "format": "格式",
    "format.codec": "编解码器",
    "codec": "编码器"
  },
  "ResolutionSelector": {
    "aspect_ratio": "宽高比",
    "megapixels": "百万像素",
    "multiple": "倍数",
    "preview": "preview"
  },
  "MarkdownNote": {},
  "LoadImage": {
    "image": "图像",
    "upload": "选择文件上传"
  },
  "ImageScaleToTotalPixels": {
    "image": "图像",
    "upscale_method": "缩放算法",
    "megapixels": "像素数量",
    "resolution_steps": "分辨率步数"
  },
  "GetImageSize": {
    "image": "图像"
  },
  "VAELoader": {
    "vae_name": "vae名称"
  },
  "VAEDecodeAudio": {
    "samples": "Latent",
    "vae": "vae"
  },
  "VAEDecode": {
    "samples": "Latent",
    "vae": "vae"
  },
  "KSamplerSelect": {
    "sampler_name": "采样器名称"
  },
  "BasicScheduler": {
    "model": "模型",
    "scheduler": "调度器",
    "steps": "步数",
    "denoise": "降噪"
  },
  "SamplerCustomAdvanced": {
    "noise": "噪波",
    "guider": "引导器",
    "sampler": "采样器",
    "sigmas": "西格玛",
    "latent_image": "Latent图像"
  },
  "BasicGuider": {
    "model": "模型",
    "conditioning": "条件"
  },
  "UNETLoader": {
    "unet_name": "UNet名称",
    "weight_dtype": "数据类型"
  },
  "CLIPLoader": {
    "clip_name": "CLIP名称",
    "type": "类型",
    "device": "设备"
  },
  "RandomNoise": {
    "noise_seed": "噪波随机种"
  },
  "CreateVideo": {
    "images": "图像",
    "audio": "音频",
    "fps": "帧率",
    "bit_depth": "bit_depth",
    "color_space": "color_space",
    "codec": "codec"
  },
  "ComfyMathExpression": {
    "values.a": "a",
    "values.b": "b",
    "expression": "表达式"
  },
  "PrimitiveFloat": {
    "value": "值"
  },
  "MiniMaxH3ReferenceToVideo": {
    "clip": "clip",
    "vae": "vae",
    "audio_vae": "audio_vae",
    "ref_images.ref_image_0": "ref_image_0",
    "ref_images.ref_image_1": "ref_image_1",
    "ref_images.ref_image_2": "ref_image_2",
    "ref_videos.ref_video_0": "ref_video_0",
    "ref_video_audios.ref_video_audio_0": "ref_video_audio_0",
    "ref_audios.ref_audio_0": "ref_audio_0",
    "ref_audios.ref_audio_1": "ref_audio_1",
    "ref_audios.ref_audio_2": "ref_audio_2",
    "prompt": "提示词",
    "width": "宽度",
    "height": "高度",
    "length": "长度",
    "ref_image_size": "参考图像尺寸"
  },
  "PrimitiveStringMultiline": {
    "value": "值"
  },
  "ComfySwitchNode": {
    "on_false": "为假时",
    "on_true": "为真时",
    "switch": "切换"
  },
  "PrimitiveInt": {
    "value": "数值"
  },
  "LoraLoaderModelOnly": {
    "model": "模型",
    "lora_name": "LoRA名称",
    "strength_model": "模型强度"
  },
  "PrimitiveBoolean": {
    "value": "值"
  },
  "MinimaxHailuo03FirstLastFrameNode": {
    "first_frame": "first_frame",
    "last_frame": "last_frame",
    "model": "model",
    "model.prompt": "prompt",
    "model.resolution": "resolution",
    "model.duration": "duration",
    "seed": "seed",
    "watermark": "watermark"
  }
};

export const OUTPUT_LABELS = {
  "SaveVideo": {
    "video": "video"
  },
  "ResolutionSelector": {
    "width": "宽度",
    "height": "高度"
  },
  "MarkdownNote": {},
  "LoadImage": {
    "IMAGE": "图像",
    "MASK": "遮罩"
  },
  "ImageScaleToTotalPixels": {
    "IMAGE": "图像"
  },
  "GetImageSize": {
    "width": "宽度",
    "height": "高度",
    "batch_size": "批处理大小"
  },
  "VAELoader": {
    "VAE": "VAE"
  },
  "VAEDecodeAudio": {
    "AUDIO": "音频"
  },
  "VAEDecode": {
    "IMAGE": "图像"
  },
  "KSamplerSelect": {
    "SAMPLER": "采样器"
  },
  "BasicScheduler": {
    "SIGMAS": "Sigmas"
  },
  "SamplerCustomAdvanced": {
    "output": "Latent",
    "denoised_output": "降噪Latent"
  },
  "BasicGuider": {
    "GUIDER": "引导器"
  },
  "UNETLoader": {
    "MODEL": "模型"
  },
  "CLIPLoader": {
    "CLIP": "CLIP"
  },
  "RandomNoise": {
    "NOISE": "噪波"
  },
  "CreateVideo": {
    "VIDEO": "视频"
  },
  "ComfyMathExpression": {
    "FLOAT": "浮点",
    "INT": "整数",
    "BOOL": "布尔值"
  },
  "PrimitiveFloat": {
    "FLOAT": "浮点"
  },
  "MiniMaxH3ReferenceToVideo": {
    "positive": "正向",
    "LATENT": "Latent"
  },
  "PrimitiveStringMultiline": {
    "STRING": "字符串"
  },
  "ComfySwitchNode": {
    "output": "输出"
  },
  "PrimitiveInt": {
    "INT": "整数"
  },
  "LoraLoaderModelOnly": {
    "MODEL": "模型"
  },
  "PrimitiveBoolean": {
    "BOOLEAN": "布尔"
  },
  "MinimaxHailuo03FirstLastFrameNode": {
    "VIDEO": "视频"
  }
};

// Global port-name fallbacks — subgraph promoted sockets (width, height, ...)
// carry no per-type entry, so ComfyUI localises them by name alone.
export const PORT_IN_LABELS = {
  "video": "视频",
  "filename_prefix": "文件名前缀",
  "format": "格式",
  "format.codec": "编解码器",
  "codec": "编码器",
  "aspect_ratio": "宽高比",
  "megapixels": "百万像素",
  "multiple": "倍数",
  "image": "图像",
  "upload": "选择文件上传",
  "upscale_method": "缩放算法",
  "resolution_steps": "分辨率步数",
  "vae_name": "vae名称",
  "samples": "Latent",
  "sampler_name": "采样器名称",
  "model": "模型",
  "scheduler": "调度器",
  "steps": "步数",
  "denoise": "降噪",
  "noise": "噪波",
  "guider": "引导器",
  "sampler": "采样器",
  "sigmas": "西格玛",
  "latent_image": "Latent图像",
  "conditioning": "条件",
  "unet_name": "UNet名称",
  "weight_dtype": "数据类型",
  "clip_name": "CLIP名称",
  "type": "类型",
  "device": "设备",
  "noise_seed": "噪波随机种",
  "images": "图像",
  "audio": "音频",
  "fps": "帧率",
  "values.a": "a",
  "values.b": "b",
  "expression": "表达式",
  "value": "值",
  "ref_images.ref_image_0": "ref_image_0",
  "ref_images.ref_image_1": "ref_image_1",
  "ref_images.ref_image_2": "ref_image_2",
  "ref_videos.ref_video_0": "ref_video_0",
  "ref_video_audios.ref_video_audio_0": "ref_video_audio_0",
  "ref_audios.ref_audio_0": "ref_audio_0",
  "ref_audios.ref_audio_1": "ref_audio_1",
  "ref_audios.ref_audio_2": "ref_audio_2",
  "prompt": "提示词",
  "width": "宽度",
  "height": "高度",
  "length": "长度",
  "ref_image_size": "参考图像尺寸",
  "on_false": "为假时",
  "on_true": "为真时",
  "switch": "切换",
  "lora_name": "LoRA名称",
  "strength_model": "模型强度",
  "model.prompt": "prompt",
  "model.resolution": "resolution",
  "model.duration": "duration"
};

export const PORT_OUT_LABELS = {
  "width": "宽度",
  "height": "高度",
  "IMAGE": "图像",
  "MASK": "遮罩",
  "batch_size": "批处理大小",
  "AUDIO": "音频",
  "SAMPLER": "采样器",
  "SIGMAS": "Sigmas",
  "output": "输出",
  "denoised_output": "降噪Latent",
  "GUIDER": "引导器",
  "MODEL": "模型",
  "NOISE": "噪波",
  "VIDEO": "视频",
  "FLOAT": "浮点",
  "INT": "整数",
  "BOOL": "布尔值",
  "positive": "正向",
  "LATENT": "Latent",
  "STRING": "字符串",
  "BOOLEAN": "布尔"
};

// How ComfyUI draws each widget (control type + option list), read from its
// node definitions — the workflow JSON only stores the values.
export const WIDGET_SPECS = {
  "SaveVideo": {
    "filename_prefix": {
      "kind": "text"
    },
    "format": {
      "kind": "combo",
      "options": [
        "auto",
        "mp4",
        "mkv",
        "webm"
      ]
    },
    "codec": {
      "kind": "combo",
      "options": [
        "auto",
        "h264",
        "av1"
      ]
    }
  },
  "ResolutionSelector": {
    "aspect_ratio": {
      "kind": "combo",
      "options": [
        "1:1 (Square)",
        "2:3 (Portrait Photo)",
        "3:2 (Photo)",
        "3:4 (Portrait Standard)",
        "4:3 (Standard)",
        "9:16 (Portrait Widescreen)",
        "16:9 (Widescreen)",
        "21:9 (Ultrawide)"
      ]
    },
    "megapixels": {
      "kind": "number"
    },
    "multiple": {
      "kind": "number"
    },
    "preview": {
      "kind": "text"
    }
  },
  "LoadImage": {
    "image": {
      "kind": "combo",
      "options": [
        "example.png"
      ]
    },
    "upload": {
      "kind": "button"
    }
  },
  "ImageScaleToTotalPixels": {
    "upscale_method": {
      "kind": "combo",
      "options": [
        "nearest-exact",
        "bilinear",
        "area",
        "bicubic",
        "lanczos"
      ]
    },
    "megapixels": {
      "kind": "number"
    },
    "resolution_steps": {
      "kind": "number"
    }
  },
  "VAELoader": {
    "vae_name": {
      "kind": "combo",
      "options": [
        "taesdxl",
        "taesd",
        "taef1",
        "pixel_space"
      ]
    }
  },
  "KSamplerSelect": {
    "sampler_name": {
      "kind": "combo",
      "options": [
        "euler",
        "euler_cfg_pp",
        "euler_ancestral",
        "euler_ancestral_cfg_pp",
        "heun",
        "heunpp2",
        "exp_heun_2_x0",
        "exp_heun_2_x0_sde",
        "dpm_2",
        "dpm_2_ancestral",
        "lms",
        "dpm_fast",
        "dpm_adaptive",
        "dpmpp_2s_ancestral",
        "dpmpp_2s_ancestral_cfg_pp",
        "dpmpp_sde",
        "dpmpp_sde_gpu",
        "dpmpp_2m",
        "dpmpp_2m_cfg_pp",
        "dpmpp_2m_sde",
        "dpmpp_2m_sde_gpu",
        "dpmpp_2m_sde_heun",
        "dpmpp_2m_sde_heun_gpu",
        "dpmpp_3m_sde",
        "dpmpp_3m_sde_gpu",
        "ddpm",
        "lcm",
        "ipndm",
        "ipndm_v",
        "deis",
        "cfgpp_ud10_ab",
        "res_multistep",
        "res_multistep_cfg_pp",
        "res_multistep_ancestral",
        "res_multistep_ancestral_cfg_pp",
        "gradient_estimation",
        "gradient_estimation_cfg_pp",
        "er_sde",
        "seeds_2",
        "seeds_3",
        "sa_solver",
        "sa_solver_pece",
        "ddim",
        "uni_pc",
        "uni_pc_bh2"
      ]
    }
  },
  "BasicScheduler": {
    "scheduler": {
      "kind": "combo",
      "options": [
        "simple",
        "sgm_uniform",
        "karras",
        "exponential",
        "ddim_uniform",
        "beta",
        "normal",
        "linear_quadratic",
        "kl_optimal"
      ]
    },
    "steps": {
      "kind": "number"
    },
    "denoise": {
      "kind": "number"
    }
  },
  "UNETLoader": {
    "unet_name": {
      "kind": "combo",
      "options": []
    },
    "weight_dtype": {
      "kind": "combo",
      "options": [
        "default",
        "fp8_e4m3fn",
        "fp8_e4m3fn_fast",
        "fp8_e5m2"
      ]
    }
  },
  "CLIPLoader": {
    "clip_name": {
      "kind": "combo",
      "options": []
    },
    "type": {
      "kind": "combo",
      "options": [
        "stable_diffusion",
        "stable_cascade",
        "sd3",
        "stable_audio",
        "mochi",
        "ltxv",
        "pixart",
        "cosmos",
        "lumina2",
        "wan",
        "hidream",
        "chroma",
        "ace",
        "omnigen2",
        "qwen_image",
        "hunyuan_image",
        "flux2",
        "ovis",
        "longcat_image",
        "cogvideox",
        "lens",
        "pixeldit",
        "ideogram4",
        "boogu",
        "krea2",
        "joyimage",
        "mage",
        "minimax",
        "yue2"
      ]
    },
    "device": {
      "kind": "combo",
      "options": [
        "default",
        "cpu"
      ]
    }
  },
  "RandomNoise": {
    "noise_seed": {
      "kind": "number"
    },
    "control_after_generate": {
      "kind": "combo",
      "options": [
        "fixed",
        "increment",
        "decrement",
        "randomize"
      ]
    }
  },
  "CreateVideo": {
    "fps": {
      "kind": "number"
    },
    "bit_depth": {
      "kind": "combo",
      "options": [
        "auto",
        8,
        10
      ]
    },
    "color_space": {
      "kind": "combo",
      "options": [
        "sRGB",
        "HDR",
        "HDR PQ"
      ]
    },
    "codec": {
      "kind": "combo",
      "options": [
        "none",
        "auto",
        "h264",
        "av1"
      ]
    }
  },
  "ComfyMathExpression": {
    "expression": {
      "kind": "text"
    },
    "values": {
      "kind": "text"
    }
  },
  "PrimitiveFloat": {
    "value": {
      "kind": "number"
    }
  },
  "MiniMaxH3ReferenceToVideo": {
    "prompt": {
      "kind": "text"
    },
    "width": {
      "kind": "number"
    },
    "height": {
      "kind": "number"
    },
    "length": {
      "kind": "number"
    },
    "ref_image_size": {
      "kind": "combo",
      "options": [
        "match",
        "max"
      ]
    },
    "ref_images": {
      "kind": "text"
    },
    "ref_videos": {
      "kind": "text"
    },
    "ref_video_audios": {
      "kind": "text"
    },
    "ref_audios": {
      "kind": "text"
    }
  },
  "PrimitiveStringMultiline": {
    "value": {
      "kind": "text"
    }
  },
  "ComfySwitchNode": {
    "switch": {
      "kind": "toggle"
    },
    "on_false": {
      "kind": "text"
    },
    "on_true": {
      "kind": "text"
    }
  },
  "PrimitiveInt": {
    "value": {
      "kind": "number"
    },
    "fixed": {
      "kind": "combo",
      "options": [
        "fixed",
        "increment",
        "decrement",
        "randomize"
      ]
    }
  },
  "LoraLoaderModelOnly": {
    "lora_name": {
      "kind": "combo",
      "options": []
    },
    "strength_model": {
      "kind": "number"
    }
  },
  "PrimitiveBoolean": {
    "value": {
      "kind": "toggle"
    }
  },
  "MinimaxHailuo03FirstLastFrameNode": {
    "model": {
      "kind": "combo",
      "options": [
        "MiniMax H3",
        "MiniMax H3 Max",
        "MiniMax H3 Max Turbo"
      ]
    },
    "seed": {
      "kind": "number"
    },
    "control_after_generate": {
      "kind": "combo",
      "options": [
        "fixed",
        "increment",
        "decrement",
        "randomize"
      ]
    },
    "watermark": {
      "kind": "toggle"
    }
  }
};
